name: mi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  jwt_decoder: ^2.0.1
  material_color_utilities: ^0.13.0
  shared_preferences: ^2.5.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/one_piece.jpg
    - assets/logo_empresa.png
    - assets/sz2.png